# Generated by Django 3.0.8 on 2020-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=50000)),
                ('publisher', models.CharField(max_length=500)),
                ('volume', models.IntegerField()),
                ('issue_no', models.CharField(max_length=500)),
                ('pages', models.CharField(max_length=500)),
                ('issue_date', models.DateField()),
                ('doi', models.CharField(max_length=500)),
                ('uri', models.CharField(max_length=500)),
                ('issn', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('type_of', models.CharField(max_length=500)),
            ],
        ),
    ]
